# this is main Portfolio info
baseURL: "https://me.farog.click/"
languageCode: en-us
title: Farog Basher
theme: PaperMod
googleAnalytics: "G-SCHV0RTLFW"

menu:
  main:
    - identifier: home
      name: Home 🏠
      url: /
      weight: 10
    - identifier: projects 
      name: Projects 👨🏻‍💻
      url: /projects
      weight: 30
    - identifier: search
      name:  Search 🔍
      url: /search
      weight: 50
    - identifier: Resume
      name: Resume 🤝
      url: "https://my-s3-pers-files.s3.us-east-2.amazonaws.com/Resume.pdf"
      weight: 60

params:
  
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Farog Basher"
    subtitle: Hi 👋 I'm Farog, As a dedicated Networking and Systems Administrator, I excel at leveraging technology to solve complex problems. With over 2 years of hands-on experience as Networking and System Admin, I specialize in designing, implementing, and managing robust IT infrastructures, with a strong focus on networking, operating systems, and ensuring security and reliability.

 
    imageUrl: "/home/me.jpg"
    imageWidth: 220
    imageHeight: 220


  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # icons and links for social media
  socialIcons:
    - name: "email"
      url: "mailto:faroog1995@hotmail.com"
    - name: "linkedin"
      url: "http://www.linkedin.com/in/farogbasher"
    - name: "github"
      url: "http://github.com/farogfayz"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true


#to build the site on production mode we should use this command
#hugo --baseURL "https://me.farog.click/"


