# this is main Portfolio infp
baseURL: "https://me.farog.click"
languageCode: en-us
title: Farog Basher
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: CV
      name: CV
      url: "https://drive.google.com/file/d/1_A7YPUN8aEAt2Jt7uGlVodCb2cv1MKx_/view?usp=sharing"
      weight: 60

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Farog Basher"
    subtitle: Hi 👋 I'm Farog, As a passionate Network and Systems Administrator, I thrive at the intersection of technology and problem-solving. Over the years of hands-on experience, I specialize in designing, implementing, and managing robust IT infrastructures using tools in network and operating systems security and reliability..

 
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # icons for social media
  socialIcons:
    - name: "email"
      url: "mailto:faroog1995@hotmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/farogbasher"
    - name: "github"
      url: "https://github.com/farogfayz"


  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
