# theme.toml template for a Hugo theme
# See http://github.com/gohugoio/hugoThemes#themetoml for an example

name = "PaperMod"
license = "MIT"
licenselink = "http://github.com/adityatelange/hugo-PaperMod/blob/master/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "http://adityatelange.github.io/hugo-PaperMod/"
demosite = "http://adityatelange.github.io/hugo-PaperMod/"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.146.0"

[author]
  name = "Aditya Telange"
  homepage = "http://github.com/adityatelange/"

# If porting an existing theme
[original]
  name = "Paper"
  author = "nanxiaobei"
  homepage = "http://github.com/nanxiaobei"
  repo = "http://github.com/nanxiaobei/hugo-paper/"
