blank_issues_enabled: false
contact_links:
  - name: PaperMod Discussions
    url: http://github.com/adityatelange/hugo-PaperMod/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.
